FROM postgres:15

COPY sql/schema.sql /schema.sql

# Install cloud-sql-proxy
RUN apt-get update && \
    apt-get install -y wget && \
    wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /usr/local/bin/cloud_sql_proxy && \
    chmod +x /usr/local/bin/cloud_sql_proxy && \
    apt-get clean

COPY init-db-script.sh /init-db-script.sh
RUN chmod +x /init-db-script.sh

CMD ["/init-db-script.sh"]
